<?php

/**
 * Implements hook_theme_suggestions_alter().
 */
function gz_theme_suggestions_theme_suggestions_alter(array &$suggestions, array $variables, $hook)
{
  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $suggestions[] = $variables['theme_hook_original'] . '__' . str_replace('-', '_', $variables['element']['#id']);
  }

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function gz_theme_suggestions_theme_suggestions_taxonomy_term_alter(array &$suggestions, array $variables) {
  $term = $variables['elements']['#taxonomy_term'];
  $suggestions[] = 'taxonomy_term__' . $term->bundle() . '__' . str_replace('-', '_', $variables['elements']['#view_mode']);;
}